# Generated by Django 6.0.3 on 2026-03-06 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFuturePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_after_graduation', models.CharField(max_length=100)),
                ('abroad_interest', models.CharField(max_length=20)),
                ('preferred_country', models.CharField(blank=True, max_length=50, null=True)),
                ('career_goal', models.CharField(max_length=100)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
