# Generated by Django 6.0.3 on 2026-03-06 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentfutureplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_completed', models.CharField(max_length=10)),
                ('internship_interest', models.CharField(max_length=10)),
                ('certification', models.CharField(max_length=10)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
